### ISSUE TITLE
npm run dev 报错 删除electron 重装也没用，安装electron时没报错

### ISSUE THREAD

**Issue by gengzhenpei** [iamdarcy/hioshop-server#21]
E:\vue\hioshop-admin\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (E:\vue\hioshop-admin\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (E:\vue\hioshop-admin\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\vue\hioshop-admin\.electron-vue\dev-runner.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by gengzhenpei** [comment]
用这个方法结局了：https://blog.csdn.net/u013584271/article/details/102764898
